alias update="DEBIAN_FRONTEND=noninteractive sudo apt update && sudo apt full-upgrade -y && sudo apt autopurge -y && sudo apt clean && flatpak update -y"
alias freemem="free -mh --si"
alias clip="xsel --clipboard --input"
alias uptime="uptime --pretty"
alias sync_watch="watch -n 1 grep -e Dirty: /proc/meminfo"
